---
title: Tokyo Hotels
title_separator: "|"
name: Hotel Zen Tokyo
description: Hotel Zen Tokyo
url: https://www.hotelzen.jp
repository: TravelTripperWeb-Sites/hotelzentokyo
email: contact@senrecube.com
default_lang: en
languages:
- en
- ja
exclude_from_localizations:
- assets/images
- assets/js
- CNAME
include:
- _pages
exclude:
- "*.sublime-project"
- "*.sublime-workspace"
- ".asset-cache"
- ".bundle"
- ".jekyll-assets-cache"
- ".sass-cache"
- Capfile
- CHANGELOG
- config
- Gemfile
- Gruntfile.js
- gulpfile.js
- LICENSE
- log
- Makefile
- media.json
- models.json
- node_modules
- old_media.json
- package.json
- package-lock.json
- Rakefile
- README
- sitemap.json
- tmp
- vendor
keep_files:
- ".git"
- assets
rsync_copy:
- assets
- _pages
- _sass
encoding: utf-8
markdown_ext: markdown,mkdown,mkdn,mkd,md
markdown: kramdown
excerpt_separator: "\n\n"
incremental: false
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
sass:
  load_paths:
  - _sass
  style: compressed
permalink: pretty
timezone: 
data_paginate:
  per_page: 5
  data: blog
  path: "/blog/page:num"
  pagination_template: blog/index.html
  sort_field: date
  sort_reverse: true
page_gen:
- data: blog
  template: post-single
  dir: "/blog/"
- data: categories
  template: category-single
  dir: "/blog/category/"
- data: offers
  template: offer-single
  dir: offers
- data: careers
  template: single-careers
  dir: "/careers/"
- data: rooms
  template: room-single
  dir: "/rooms/"
